name: lint-and-test

on:
  push:
    branches:
      - '**'
    tags-ignore:  # Don't double-run for tags
      - '**'

jobs:
  lint-and-test:  # Additional linting done by pre-commit.ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools importlib-metadata
        pip install poetry
        poetry install

    - name: Run flake8
      run: poetry run flake8 .

    - name: Run mypy
      run: poetry run mypy ./src
      if: always()

    - name: Run pytest
      run: poetry run pytest
      if: always()
